### PR TITLE
Instrument model created -need to updated references to

### PR DESCRIPTION
**Pull request by davidavidavidavidavidave**
instrument model created, and references to add.

### CODE REVIEW

**Review by davidavidavidavidavidave — COMMENTED** [review]
Instrument model successfully created. To do references

**Review by ThomasJW87 — COMMENTED** [review]
Happy with model creation

**Comment by ThomasJW87** [comment]
Model creation for instrument done without references to, will create these with future commit

**Comment by ThomasJW87** [comment]
Model creation for instrument done without references to, will create these with future commit

**Review by ThomasJW87 — APPROVED** [review]

**Pull request merged**
